[[IgnoredVulns]]
id = "GHSA-2p57-rm9w-gvfp"
reason = "pkg: ip - npte: SSRF attacks not relevant to our usage of Meerkat"

[[IgnoredVulns]]
id = "GHSA-4hjh-wcwx-xvwj"
reason =  "pkg: axiox (dev) - note: e2e tests"

[[IgnoredVulns]]
id = "GHSA-52f5-9888-hmc6"
reason = "pkg: tmp (dev) - note: e2e tests"
