[[IgnoredVulns]]
id = "GHSA-2p57-rm9w-gvfp"
reason = "pkg: ip - note: SSRF attacks not relevant to our usage of Meerkat"

[[IgnoredVulns]]
id = "GHSA-4hjh-wcwx-xvwj"
reason =  "pkg: axiox (dev) - note: e2e tests"

[[IgnoredVulns]]
id = "GHSA-52f5-9888-hmc6"
reason = "pkg: tmp (dev) - note: e2e tests"

[[IgnoredVulns]]
id = "GHSA-jr5f-v2jv-69x6"
reason = "pkg: axios (dev) - note: e2e tests"

[[IgnoredVulns]]
id = "GHSA-v6h2-p8h4-qcjw"
reason = "pkg: brace-expansion (dev) - note: e2e tests or linting - low risk"

[[IgnoredVulns]]
id = "GHSA-fjxv-7rqg-78g4"
reason = "pkg: form-data (dev) - note: e2e tests"

[[IgnoredVulns]]
id = "GHSA-5j98-mcp5-4vw2"
reason = "pkg: glob (dev) - note: e2e tests"

[[IgnoredVulns]]
id = "GHSA-mh29-5h37-fv8m"
reason = "pkg: js-yaml (dev) - note: Only reads our config or jest/eslint related so little to no risk"

[[IgnoredVulns]]
id = "GHSA-76c9-3jph-rj3q"
reason = "pkg: on-headers (dev) - note: e2e tests"

[[IgnoredVulns]]
id = "GHSA-rv73-9c8w-jp4c"
reason = "pkg: validate.js (dev) - note: e2e tests"
