name: dependency-check-owasp-ios

on:
  push:
    paths: &shared-trigger-paths
      - "**/Podfile.lock"
      - "**/Package*.swift"
      - ".github/workflows/dependency-check-owasp-ios.yml"
    branches:
      - main
      - develop
      - 'releases/**'
  pull_request:
    paths: *shared-trigger-paths
    types: [ opened, synchronize ]

jobs:
  depcheck:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: "package.json"

      - name: Install dependencies
        run: npm ci

      # Run OWASP Dependency-Check via the official Action
      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@2ba636726705b0f74f126ebeaacaf2ad4600b967 # main at 01/10/2025
        with:
          project: "veridian-wallet-ios"
          path: "ios"
          format: "ALL"
          out: "reports"
          args: "--failOnCVSS 7 --nvdApiKey ${{ env.NVD_API_KEY }} -s **/Podfile.lock"
        continue-on-error: false

      - name: Upload HTML report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: depcheck-ios-report
          path: "reports/dependency-check-report.html"

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 # v3.30.5
        with:
          sarif_file: "reports/dependency-check-report.sarif"
